services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=remitlydb
      - DB_NAME=v1
      - DB_PORT=3306
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=remitlydb
      - MYSQL_DATABASE=v1
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
